-- CreateEnum
CREATE TYPE "Tag" AS ENUM ('BREAKFAST', 'BRUNCH', 'LUNCH', 'DINNER', 'SNACK', 'DESSERT', 'APPETIZER', 'SIDE_DISH', 'SOUP', 'SALAD', 'SAUCE', 'DRINK', 'HUNGARIAN', 'ITALIAN', 'MEXICAN', 'AMERICAN', 'FRENCH', 'GREEK', 'SPANISH', 'INDIAN', 'THAI', 'JAPANESE', 'CHINESE', 'KOREAN', 'MIDDLE_EASTERN', 'VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'GLUTEN_FREE', 'DAIRY_FREE', 'LOW_CARB', 'HIGH_PROTEIN', 'QUICK', 'EASY', 'MEAL_PREP', 'MAKE_AHEAD', 'FREEZER_FRIENDLY', 'ONE_POT', 'SHEET_PAN', 'SLOW_COOKER', 'PRESSURE_COOKER', 'AIR_FRYER', 'GRILLED', 'BAKED', 'NO_BAKE', 'COMFORT_FOOD', 'WEEKDAY', 'PARTY', 'HOLIDAY', 'SUMMER', 'WINTER', 'SPICY', 'SWEET');

-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN     "tags" "Tag"[];
